<?php

use Illuminate\Database\Seeder;
use App\Project;
class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $projecta=new Project();
        $projecta->id=4;
        $projecta->title="CASI - Centralized Admission System of IOE >> काजी";
        $projecta->summary="Automation of admission process for all of our campuses/colleges";
        $projecta->projectData="<h1 style='text-align:center'>CASI - Centralized Admission System of IOE &gt;&gt; काजी</h1><p>Continuous improvement in the academic environment and achieving excellence in producing quality engineers is the main motto of IOE. After automating the BE &amp; M.Sc. entrance system, IOE is proceeding towards the automation of admission process for all of its campuses/colleges where the research study carried out in 2016 thoroughly investigated the existing system and recommend reform in admission process of IOE. We, the member of that research team reviewed the study documents and propose the suitable administrative and technical framework for the automation of IOE admission system.&nbsp;CASI&nbsp;is a research based projects implemented for the uniformity in admission process at all constituent campuses and the affialiated colleges of Institute of Engineering towards excellency by enrolling meritorious best students every year at its engineering education.&nbsp;<br />
        The enrollment software systems developed is running from&nbsp;<a href='http://admission.ioe.edu.np/' target='_blank'>http://admission.ioe.edu.np</a>&nbsp;and is contineous progress in optimum implementation</p>";
        $projecta->save();
        $projecta=new Project();
        $projecta->id=5;
        $projecta->title="Real Time Intranet based Entrance ExamiNAtion System (RETIENAS) रेटिनाज";
        $projecta->summary="The fully managed and hassle free application processing system of IOE entrance examination allows applicants to simply apply and receive admit card with specified time slot.";
        $projecta->projectData="<h1 style='text-align:center'>Real Time Intranet based Entrance ExamiNAtion System (RETIENAS) रेटिनाज</h1>

        <p>RETIENAS is a research and development project initiated by Prof. Dr. Bharat Raj Pahari, formar Dean of Institute of Engineering (IOE), Tribhuvan University (TU) on 2012 with the objective to select highly qualified candidates by having sohpisticated computer based entrance examination system for bachelor/master level engineering study at the institute. IOE is the government owned oldest institution in Nepal providing quality education in the engineering domain since 1972. However in the recent decade, other several universities are established in the country, IOE hasn&#39;t lost its popularity with its major features to have dedication on quality education to fulfill the world class standards in education. As a public institution, it provides equal opportunities for all qualified citizens to enter into the university education. There are generally more than 11,000 competitive applicants in the entrance exam of bachelors program. Hence less than 32% students were selected for the admission.&nbsp;<br />
        As being the technical institute, historically IOE is always ahead in the use of technology. The increasing burden in the manual processing of the entrance exam enforces IOE to step into the automatic exam oepration and result processing system. In 2004, IOE developed automatic answer sheet scanning and processing system and started online based application since 2009. From the year 2014, IOE has started fully computer based entrance examination at its resourceful centers (ICTC) at Pulchowk. The fully managed and hassle free application processing system of IOE entrance examination (<a href='http://entrance.ioe.edu.np/' target='_blank'>&nbsp;http://entrance.ioe.edu.np</a>) allows applicants to simply apply and receive admit card with specified time slot from online registration system.&nbsp;<br />
        Project RETIENAS had been executed since 2012 and is currently led by dean of Institute of Engineering Prof. Dr. Triratna Bajracharya including highly qualified research oriented faculties of IOE. RETIENAS has the following features:&nbsp;</p>
        
        <ul>
            <li>It is an automated system for Application Registration, Processing, Verification and Admit Card Generation for BE/BArch as well as M.Sc. Entrance Examination</li>
            <li>The system also reserved the exam date and time slot for every applicants.</li>
            <li>Highly secured intrancet system is available at Information and Communication Technology Center at IOE Pulchowk. Students appear in the center and give exam from specified LAB and the computer.</li>
            <li>The redundant entrance examination servers (WEB,DB) are maintained and more than 240 client computers are dedicately placed at ICTC. Hence 240 examinees can appear at a time for the examination</li>
            <li>The Entrance Examination Board of IOE massively conducts yearly entrance exam by planning four slots in a day and one slot consists of 240 examinees. Hence, it takes almost 10 to 12 days to conduct exam for about 11,000 applicants.</li>
        </ul>
        
        <p>The deveoped package to conduct entrance examination is fully interactive client server based system in which the time between server and client is well synchronized. We implemented lamports timestamp with the cristian&#39;s clock synchronization algorithm to distribute updated timestamp from server. Since the system is on the single LAN (Intranet), hence the propagation delay between client and server for timestamp distribution is very little (in micro-second) that does not considerably affect examinees during examination.&nbsp;<br />
        LICT team is continuing the research and development (upgrade) of the system to make it fully distributed and run on multiple LAN with the introdcution of CACHE servers to balance the load and increase the concurrent access during examination so that we can increase the number of examinees in a slot.</p>
        
        <h3><strong>Glimpse of ICTC Computer Labs:</strong></h3>
        
        <p><strong><img alt='' src='../../project/project5-1.jpg' style='height:50%; width:100%' /></strong></p>
        
        <p><strong><img alt='' src='../../project/project5-2.jpg' style='height:50%; width:100%' /></strong></p>";
        $projecta->save();
        $projecta=new Project();
        $projecta->id=6;
        $projecta->title="Semester Exam AuTomation System of IOE (SETISI) सेटिसी";
        $projecta->summary="Inhouse ICT Research and Development Project initiated to automate the Semester Exam activities of IOE.";
        $projecta->projectData="<h1 style='text-align:center'>&nbsp; &nbsp;&nbsp;Semester Exam AuTomation System of IOE (SETISI) सेटिसी</h1>

        <p>SETISI is an inhouse ICT Research and Development Project initiated to automate the Semester Exam activities of IOE. Examination Control Division (ECD) of Institute of Engineering, Tribhuvan University is the one prominent and most busy organization where it conducts several examinations throughout the year. ECD conducts bi-annual semester exams for regular and back exam of bachelor of engineering students having 10 streams in its four constituent campuses and ten affiliated colleges. Similarly, ECD also conducts bi-annual exams for masters of engineering programs having seven streams and 21 sub-streams. Hence tentatively, there are more than 16000 examinees in an exam including regular and back. Additionally, successful conduction of BE/BArch entrance examination as well as M.Sc. entrance examination is the part of examination to be conducted by ECD.<br />
        Examination registrations of all programs, exam center management, examinees detail verifications, exam roll number and admit card generations, collections of internal, projects, survey marks and its processing/verifications, coding/decoding of the answer sheets, packaging, expert assignments, air and ground transportations and delivery of packets/question, tracking of packets, secure result processing and result publications, question setting arrangement, re-totaling managements, error correction and verification and many more are the quite challenging events continuously to be handled by ECD of IOE requiring more human resources and time critical management of all activities to adapt with the pre-defined IOE calendar.&nbsp;<br />
        The increase of streams and examinees demand more on all other relevant resources making the system more complex for operation and management within the existing non-automated manual system environment. Hence, to consider the efficient, reliable, secure and transparent operation and management of the system, a research towards the automation process of ECD has been initiated with the development of the software and its implementation in a planned way. The whole system development at a time shall be complicated and costly too. We are developing the automated system and implementing by developing it in modules with the principle of rapid application development so that while implementing one module encourages for analysis and design of other relevant modules.&nbsp;<br />
        ECD already has secure result processing system for BE/BArch programs. While online based exam registrarion, procfessing and admit card generation as well as M.Sc. result processing and publications modules are under development</p>";
        $projecta->save();
        $projecta=new Project();
        $projecta->id=7;
        $projecta->title="Transformation to Future Networking with Broadband and IoT Implementations: Status of Nepal and the Steps Ahead (TraFNet)";
        $projecta->summary="Transformation to Future Networking with Broadband and IoT Implementations";
        $projecta->projectData="<h1 style='text-align:center'>T<strong>ra</strong><strong>nsformation to</strong><strong>&nbsp;F</strong><strong>uture&nbsp;</strong><strong>Net</strong><strong>working with Broadband and IoT Implementations: Status of Nepal and the Steps Ahead (TraFNet)</strong></h1>

        <p>&nbsp;</p>
        
        <h2>Research Motivation</h2>
        
        <p>We, the research team members include professionals of networking and telecommunications as well as university professors. Our main motto is to have localized ICT research for our country that contributes towards speedy implementation of new technologies in the field of information and communication technology for social transformation. At the different time frame, we members were involved in real time network configuration of telecom networks, ICT policy formulation including IPv6 migration, broadband communication, latest network deployment et cetera. It was also the major concern of Nepal Telecommunications Authority (NTA) to formulate suitable policies and regulatory guidelines to transform the current network into new networking paradigms. The important part for our country is the identification of proper cost of broadband deployment as well as network migration for ISP and Telecom equipment upgrades towards IPv6 and Software Defined Network (SDN), Implementation for Internet of Things (IoT), network operation &amp; maintenance and upgrade as well. Another major concern is the amount of energy consumed by networks. The increasing network size and continuous operation increase the energy consumption by the network devices. Because of this, the companies pay a significant percentage of their revenue to power their network infrastructures. With the rapid growth of smart users, IoT implementation and the Wireless Sensor Network (WSN) deployment becomes major concern for the service providers as their sustainable business solutions. Considering the global pace of technology transformations, we need to take steps for our country&rsquo;s network to identify its current status and apply suitable measures towards future smart life.&nbsp;<br />
        This seismic shift in the technological paradigm has encouraged the team to carry out practical research on the field of smart cities and the related infrastructure including IoT, carrier network and data analytics infrastructure along with evolutionary enablers such as IPv6, Software Defined Networks (SDN), cloud computing infrastructure and virtualization technologies. These technological enablers are critical in realizing a functional high-tech society that can lead to efficient service delivery, better communication and improved quality of life in the smart communities.&nbsp;</p>
        
        <h2>Background</h2>
        
        <p>Internet and related technologies have transformed the way humans communicate. Rapid technological advancement, service proliferation and integration of innumerable services have made the Internet an indispensable part of our lives. Traditionally, Internet has been a means of communication between people. The technology and network enabled people to quickly communicate with each other irrespective of geographical distance. This network then led to the evolution of network based services in trade, finance, education, social networking, and public services delivery. Even conventional communication media such as voice telephony and short messaging services are becoming Internet-borne.&nbsp;<br />
        Lately, Internet and IP technology have taken another very transformative turn. Machines have started to get more autonomous as connected entities that can create and consume data. This traditionally human activity (of creating and consuming data) has started being done by machines in what is known as M2M (Machine to Machine) network. This phenomena combined with the Internet technology is also called the Internet of Things (IoT). This has created an unprecedented avenue of technological evolution and business opportunity. Concepts such as remote surveillance, smart cities, smart homes, societal automation are becoming a reality. This, combined with advanced data analytics technologies, artificial intelligence, cloud platforms, rapid expansion of next generation broadband networks (wired and wireless) for seamless communication and future-proof technologies such as IPv6 has made the dream of smart communities, industrial automation and automated public service delivery a reality.<br />
        According to the gadget survey within the last 20 years, the number of Internet users reached more than 3 billion. The number of connected devices is more than 7.2 billion mobile gadgets which is even bigger than world&#39;s population in 2015. The rapid growth of Internet users and ICT business in the world led to the exhaustion of IPv4 address space and forced the industry to standardize new addressing scheme having 128 bits, called Internet Protocol version 6 (IPv6). In the next generation networking infrastructure, every connected device shall have one or more unique IPv6 addresses. The vast size of the IPv6 address space has enough addresses to allocate to every such device coming up in the foreseeable future. IPv6 on the one hand improves the efficiency of internet protocol as a whole including routing, while on the other hand Software Defined Networks (SDN) improves the controllability of networking equipment with an approach to using open protocols, such as Open-Flow, to apply globally aware software control at the edges of the network to access network devices that typically would use closed and vendor specific firmware. The invention of these new concepts and development creates bigger challenges in networking for service providers to migrate their existing legacy networks into the software defined and IPv6 enabled network and the implementation of those technologies in broadband communications.&nbsp;<br />
        With the rapid growth of internet users, increased Internet of Things (IoT), smart devices and the trend of world moving to converged network environment into the mode of computer networks (IP based network), the researchers, developers and the networking enterprises worldwide are obliged to enhance the intelligence in networking technologies. For the realization of the dream of smart cities and smart communities it is imperative to move towards next generation networking paradigm like IPv6 addressing mechanism, Software Defined Network as well as implementing the IoT &amp; Wireless Sensor Network and addressing the increased user&rsquo;s demand by having high speed broadband communications.&nbsp;<br />
        Being the developing country, Nepal is a net consumer of Internet services and technologies. ISPs of Nepal are the distributors of technologies and services. However, the rapid changes in technology worldwide has raised the challenges and issues for the developing country like Nepal towards the early implementation of evolving and new services. The major hurdles are limited skilled human resources, limited purchasing capacity and lack of proper planning. There is also a need for proper and timely government initiatives to formulate the policies, laws and regulation as well as their proper enforcement to usher in desired change in relevant sectors of society.</p>
        
        <p>Nepal has six licensed telecom operators and more than 60 ISPs. Recently promulgated broadband policy of Nepal is still in the initial stage of implementation while the sufficient study on technology migration, migration policy and strategy have not been set by the government. The change in technologies encourages and prompts the service providers to introduce new technologies and provide efficient services to the customers via technology migration. The migration is a gradual process for which proper strategy has to be developed by the service providers considering the technology needs, customer demand, Capital Expenditure (CapEX), Operational Expenditure (OpEX) and traffic engineering perspectives towards smooth transitioning. The transition period spans longer during when the service providers should have to move forward with proper migration planning with optimum cost. On the other hand the geographical distribution of Nepal is unique in the world having highest peak, mostly covered by Himalayan, hilly diverse terrain and a small part of plain area. Difficult geographical terrain and scattered inhabitation makes it difficult to build communication infrastructure and distribute the technologies and services. Core network migration to IPv6 and SDN, broadband infrastructure deployment with proper policy to suit of those migrated new technologies and the IoT implementations are the major concerns for the service providers of developing countries like Nepal. Looking into the Nepalese context, the technology migration is in the early stage. Similarly the broadband deployment, cloud computing, IoT implementations together with the necessary policy and implementation guideline formulation are in the early stages. This encouraged us to undertake this localized ICT research for our country so that we find the current status of technology implementation and recommend for the future that helps the country towards smart life and reduce the digital divide. We also expect the research to provide important insight to help innovate and introduce new services with right technologies in an effective and economical manner.</p>
        
        <h2>Justification of the Study</h2>
        
        <p>This research performs the technical and economic analysis of the legacy network migration to Software Defined IPv6 Network with broadband deployment challenges for Nepal including IoT implementation and the security measure that the service providers should consider. It will focus to identify networking equipment status for their upgradability towards future networking, optimum estimate to migrate the service provider network with cost of migration and broadband network deployment and identify the IoT implementation plan with better security.&nbsp;<br />
        <strong>Technological Impact:</strong>&nbsp;This research is highly assistive to the service providers of Nepal to efficiently migrate their current network into next generation networking paradigm like SDN &amp; IPv6 as well as it comes up with proper plan and strategies for broadband deployment and IoT implementations.<br />
        <strong>Socio economic impact:</strong>&nbsp;organizations and the citizens are directly benefited with the use of low cost and affordable new ICT services.&nbsp;<br />
        This research would also be helpful to the government agencies/regulators for proper regulation, development of regulatory guidelines/rules and future planning.</p>
        
        <h2>Objective(s)</h2>
        
        <p>The major objective(s) of this faculty research shall be as follows</p>
        
        <ol start='1' style='list-style-type:decimal'>
            <li>Study the current trend of networking technologies migrations including broadband deployment and the IoT implementation for future smart life</li>
            <li>Find the position of Nepal regarding Broadband deployment, SDN/IPv6 migration &amp; IoT implementation.</li>
            <li>Analyze the future network transformation challenges and recommend the solution for Nepal.</li>
        </ol>
        
        <p><strong>Reserach Duration: 2 Years</strong></p>
        
        <p><strong>This research is</strong></p>
        
        <ul>
            <li>Academically supported by Center for Applied Research and Development, Institute of Engineering in collaboration with NTNU (Norwegian University of Science and Technology) under Sustainable Engineering Education Project (SEEP) and financed by the Energy and Petroleum Program (EnPe) in NORAD (Norwegian Agency for Development Cooperation) and Nepal Academy of Science and Technology</li>
            <li>Requested to University Grant Commission Nepal (UGC-Nepal) for funding support of up to 4 Lakhs under faculty research grant.</li>
        </ul>";
        $projecta->save();
    }
}
