<?php

use Illuminate\Database\Seeder;
use App\User;
class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        $user=new User();
        $user->id=9;
        $user->name="ram";
        $user->password=Hash::make('ram5921');
        $user->FirstName="Prof. Ram";
        $user->LastName="Sapkota";
        $user->MiddleName="Chandra";
        $user->ioePost="Dean";
        $user->contactphone="";
        $user->email="rc.sapkota1@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-9.png";
        $user->personalURL="";
        $user->lictTitle="";
        $user->lictType=4;
        $user->Remarks="Chair of Entrance Examination Board of Institute of Engineering, Tribhuvan Unviersity";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=8;
        $user->name="Triratna";
        $user->password=Hash::make('Triratna5311');
        $user->FirstName="Prof. Dr. Triratna";
        $user->LastName="Bajracharya";
        $user->MiddleName="";
        $user->ioePost="Ex-Dean @IOE & Full Professor of Mechanical Engineering";
        $user->contactphone="";
        $user->email="";
        $user->imgPathName="userfiles/profile-photo-8.png";
        $user->personalURL="";
        $user->lictTitle="";
        $user->lictType=4;
        $user->Remarks="Founder of this research LAB";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=10;
        $user->name="jagat";
        $user->password=Hash::make('jagat6811');
        $user->FirstName="Dr. Jagat";
        $user->LastName="Shrestha";
        $user->MiddleName="Kumar";
        $user->ioePost="Asst. Dean, Academic Administration";
        $user->contactphone="";
        $user->email="";
        $user->imgPathName="userfiles/profile-photo-10.png";
        $user->personalURL="";
        $user->lictTitle="";
        $user->lictType=4;
        $user->Remarks="Faculty of Civil Engineering";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=11;
        $user->name="nagendra";
        $user->password=Hash::make('nagendra7896');
        $user->FirstName="Reader Nagendra";
        $user->LastName="Amatya";
        $user->MiddleName="Bahadur";
        $user->ioePost="Asst. Dean, Academic";
        $user->contactphone="";
        $user->email="";
        $user->imgPathName="userfiles/profile-photo-11.png";
        $user->personalURL="";
        $user->lictTitle="";
        $user->lictType=4;
        $user->Remarks="Faculty of Mathematics";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=12;
        $user->name="sushil";
        $user->password=Hash::make('sushil1564');
        $user->FirstName="Prof. Dr. Sushil";
        $user->LastName="Bajracharya";
        $user->MiddleName="Bahadur";
        $user->ioePost="Asst. Dean, Planning";
        $user->contactphone="";
        $user->email="";
        $user->imgPathName="userfiles/profile-photo-12.png";
        $user->personalURL="";
        $user->lictTitle="";
        $user->lictType=4;
        $user->Remarks="Faculty of Architecture";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=13;
        $user->name="sailendra";
        $user->password=Hash::make('sailendra4680');
        $user->FirstName="Prof. Dr. Sailendra";
        $user->LastName="Mishra";
        $user->MiddleName="Kumar";
        $user->ioePost="Director, Center for Applied Research and Development (CARD)";
        $user->contactphone="";
        $user->email="";
        $user->imgPathName="userfiles/profile-photo-13.png";
        $user->personalURL="http://card.ioe.edu.np";
        $user->lictTitle="";
        $user->lictType=4;
        $user->Remarks="Faculty of Mathematics";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=14;
        $user->name="shashidhar";
        $user->password=Hash::make('shashidhar4760');
        $user->FirstName="Prof. Dr. Shashidhar";
        $user->LastName="Joshi";
        $user->MiddleName="Ram";
        $user->ioePost="Full Professor, IOE Pulchowk Campus";
        $user->contactphone="";
        $user->prvProfile="https://lict.ioe.edu.np/profile/srjoshi/";
        $user->email="srjoshi@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-14.png";
        $user->personalURL="";
        $user->lictTitle="Chairman";
        $user->lictType=3;
        $user->Remarks="Faculty of Computer and Knowledge Engineering";
        $user->researchAreas="ICT & Green Computing, Image Processing, Neural Network";
        $user->save();
        $user=new User();
        $user->id=15;
        $user->name="sanjeeb";
        $user->password=Hash::make('sanjeeb8290');
        $user->FirstName="Assoc. Prof. Dr. Sanjeeb";
        $user->LastName="Panday";
        $user->MiddleName="Prasad";
        $user->ioePost="Director, Information and Communication Technology Center (ICTC)";
        $user->contactphone="";
        $user->email="sanjeeb@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-15.png";
        $user->personalURL="";
        $user->prvProfile="https://lict.ioe.edu.np/profile/sanjeeb/";
        $user->lictTitle="Co-Chairman";
        $user->lictType=3;
        $user->Remarks="Faculty of Computer and Knowledge Engineering";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=16;
        $user->name="baburam";
        $user->password=Hash::make('baburam5613');
        $user->FirstName="Lec. Babu";
        $user->LastName="Dawadi";
        $user->MiddleName="Ram";
        $user->prvProfile="http://www.baburd.com.np/";
        $user->publications="https://scholar.google.com/citations?user=Ez88p3kAAAAJ&hl=en";
        $user->ioePost="Research Scholar";
        $user->contactphone="+9779841340354";
        $user->email="baburd@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-16.png";
        $user->personalURL="http://www.baburd.com.np";
        $user->lictTitle="Vice-Chairman";
        $user->lictType=3;
        $user->Remarks="Faculty of Computer and Knowledge Engineering";
        $user->researchAreas="Networking (SDN, IPv6), Distributed Computing";
        $user->save();
        $user=new User();
        $user->id=17;
        $user->name="sarad";
        $user->password=Hash::make('sarad5613');
        $user->FirstName="Lec. Sarad";
        $user->LastName="Ghimire";
        $user->prvProfile="https://lict.ioe.edu.np/profile/skghimire/";
        $user->MiddleName="Kumar";
        $user->ioePost="Deputy Director, ICTC, IOE";
        $user->contactphone="";
        $user->email="skghimire@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-17.png";
        $user->personalURL="";
        $user->lictTitle="Member";
        $user->lictType=3;
        $user->Remarks="Faculty of Computer and Knowledge Engineering";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=18;
        $user->name="aman";
        $user->password=Hash::make('aman2463');
        $user->FirstName="Lec. Dr. Aman";
        $user->LastName="Shakya";
        $user->MiddleName="";
        $user->prvProfile="https://lict.ioe.edu.np/profile/aman/";
        $user->ioePost="Program Coordinator, M.Sc. Computer System & Knowledge Engg.";
        $user->contactphone="+9779841218877";
        $user->email="aman.shakya@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-18.png";
        $user->personalURL="";
        $user->lictTitle="Member";
        $user->lictType=3;
        $user->Remarks="Faculty of Computer and Knowledge Engineering";
        $user->researchAreas="Semantic Web, Linked open data, web 2.0, social semantics, XML, Natural Language Processing";
        $user->save();
        $user=new User();
        $user->id=19;
        $user->name="daya";
        $user->password=Hash::make('daya2363');
        $user->FirstName="Lec. Daya";
        $user->LastName="Baral";
        $user->MiddleName="Sagar";
        $user->ioePost="Director, Center for Information Technology, Pulchowk Campus";
        $user->contactphone="";
        $user->prvProfile="https://www.dsbaral.com.np/";
        $user->email="dsbaral@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-19.png";
        $user->personalURL="http://www.dsbaral.com.np/";
        $user->lictTitle="Member";
        $user->lictType=3;
        $user->Remarks="Faculty of Information and Communication Engineering";
        $user->researchAreas="Networking, Cloud Computing";
        $user->save();
        $user=new User();
        $user->id=20;
        $user->name="basanta";
        $user->password=Hash::make('basanta8465');
        $user->FirstName="Lec. Dr. Basanta";
        $user->LastName="Joshi";
        $user->MiddleName="Sagar";
        $user->prvProfile="http://www.basantajoshi.com.np/";
        $user->publications="http://www.basantajoshi.com.np/publications/";
        $user->ioePost="Program Coordinator, M.Sc. in Information and Communication Engg.";
        $user->contactphone="+9779851190040";
        $user->email="basanta@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-20.png";
        $user->personalURL="http://www.basantajoshi.com.np/";
        $user->lictTitle="Member";
        $user->lictType=3;
        $user->Remarks="Faculty of Information and Communication Engg.";
        $user->researchAreas="Artificial Intelligence and Application of machine Learning in Image Processing, Speech Processing and Big data.";
        $user->save();
        $user=new User();
        $user->id=21;
        $user->name="vipul";
        $user->password=Hash::make('vipul8465');
        $user->FirstName="Er. Vipul";
        $user->LastName="Gautam";
        $user->MiddleName="";
        $user->ioePost="Computer System Analyst";
        $user->contactphone="9841350299";
        $user->email="vipul@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-21.png";
        $user->personalURL="";
        $user->lictTitle="Researcher";
        $user->lictType=3;
        $user->Remarks="Computer & Network System and Security";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=22;
        $user->name="sharadthapa";
        $user->password=Hash::make('sharadthapa8465');
        $user->FirstName="Sharad";
        $user->prvProfile="https://lict.ioe.edu.np/profile/skthapa/";
        $user->LastName="Thapa";
        $user->MiddleName="Kumar";
        $user->ioePost="Administrator/Account Officer";
        $user->contactphone="+9779841751913";
        $user->email="sharadthapa@ioe.edu.np";
        $user->imgPathName="userfiles/profile-photo-22.png";
        $user->personalURL="";
        $user->lictTitle="Account-Officer";
        $user->lictType=3;
        $user->Remarks="Account Officer of Examination Control Division, Institute of Engineering";
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=23;
        $user->name="nabin";
        $user->password=Hash::make('nabinkhanal123');
        $user->FirstName="Nabin";
        $user->LastName="Khanal";
        $user->contactphone="+9779843816009";
        $user->email="073bct524.nabin@pcampus.edu.np";
        $user->imgPathName="userfiles/profile-photo-23.png";
        $user->lictType=1;
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=24;
        $user->name="kpp";
        $user->password=Hash::make('krishnapanthi123');
        $user->FirstName="Krishna";
        $user->MiddleName="Prasad";
        $user->LastName="Panthi";
        $user->contactphone="+9779867143712";
        $user->email="073bct519.krishna@pcampus.edu.np";
        $user->imgPathName="userfiles/profile-photo-24.png";
        $user->lictType=1;
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=25;
        $user->name="krishna";
        $user->password=Hash::make('krishnadhakal123');
        $user->FirstName="Krishna";
        $user->LastName="Dhakal";
        $user->contactphone="+9779861028227";
        $user->email="073bct518.krishna@pcampus.edu.np";
        $user->imgPathName="userfiles/profile-photo-25.png";
        $user->lictType=1;
        $user->researchAreas="";
        $user->save();
        $user=new User();
        $user->id=26;
        $user->name="Buddha";
        $user->password=Hash::make('buddha12345');
        $user->FirstName="Buddha";
        $user->MiddleName="Thapa";
        $user->LastName="Magar";
        $user->contactphone="+9779860086162";
        $user->email="073bct512.buddha@pcampus.edu.np";
        $user->imgPathName="userfiles/profile-photo-26.png";
        $user->lictType=1;
        $user->researchAreas="";
        $user->save();
    }
}
